"""
Chat API endpoints with streaming support
"""

from fastapi import APIRouter, WebSocket, WebSocketDisconnect, HTTPException, Depends
from fastapi.responses import StreamingResponse
from typing import AsyncGenerator
import json
import uuid
from datetime import datetime

from src.retrieval.models.requests import ChatRequest, StreamChatRequest
from src.retrieval.models.responses import (
    ChatResponse, ChatHistoryResponse, ChatMessage, SourceCitation
)
from src.retrieval.services.retrieval_service import RetrievalService
from src.retrieval.services.llm_service import LLMService
from src.retrieval.api.dependencies import get_retrieval_service, get_llm_service


router = APIRouter()

# In-memory conversation store (use Redis/DB in production)
_conversations = {}


@router.post("/query", response_model=ChatResponse)
async def chat_query(
    request: ChatRequest,
    retrieval_service: RetrievalService = Depends(get_retrieval_service),
    llm_service: LLMService = Depends(get_llm_service)
) -> ChatResponse:
    """
    Standard chat query with RAG retrieval.

    Supports configurable search settings:
    - hybrid_search: Use dense + sparse + RRF (default: true)
    - reranking: Use cross-encoder reranking (default: true)

    Returns complete response (non-streaming).
    """
    try:
        # Generate conversation ID if not provided
        conversation_id = request.conversation_id or str(uuid.uuid4())

        # Build settings dict from request
        search_settings = {
            "hybrid_search": request.hybrid_search if request.hybrid_search is not None else True,
            "reranking": request.reranking if request.reranking is not None else True,
            "dense_k": request.dense_k or 50,
            "sparse_k": request.sparse_k or 50,
            "rerank_k": request.rerank_k or 20,
            "final_k": request.top_k or 5,
        }

        # 1. Retrieve relevant documents with settings
        search_results = await retrieval_service.search_with_settings(
            query=request.query,
            settings=search_settings,
            filters=request.filters
        )

        # 2. Format context for LLM
        context = []
        sources = []
        for result in search_results:
            context.append({
                "content": result.content,
                "source": result.document_id
            })
            sources.append(SourceCitation(
                chunk_id=result.chunk_id,
                document_id=result.document_id,
                content=result.content[:200] + "..." if len(result.content) > 200 else result.content,
                score=result.score,
                reranked_score=result.reranked_score,
                metadata=result.metadata
            ))

        # 3. Generate response with LLM
        answer = await llm_service.generate_response(
            query=request.query,
            context=context,
            system_prompt="You are a helpful assistant. Answer the user's question based on the provided context. If the context doesn't contain the answer, say so."
        )

        # 4. Store conversation (simplified - use proper DB in production)
        if conversation_id not in _conversations:
            _conversations[conversation_id] = []

        _conversations[conversation_id].append(ChatMessage(
            role="user",
            content=request.query,
            timestamp=datetime.now().isoformat()
        ))

        _conversations[conversation_id].append(ChatMessage(
            role="assistant",
            content=answer,
            timestamp=datetime.now().isoformat(),
            sources=sources
        ))

        return ChatResponse(
            conversation_id=conversation_id,
            answer=answer,
            sources=sources
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Chat query failed: {str(e)}"
        )


@router.post("/stream")
async def chat_stream(
    request: StreamChatRequest,
    retrieval_service: RetrievalService = Depends(get_retrieval_service),
    llm_service: LLMService = Depends(get_llm_service)
) -> StreamingResponse:
    """
    Streaming chat query with Server-Sent Events.

    Streams tokens as they are generated by the LLM.
    """

    async def event_generator() -> AsyncGenerator[str, None]:
        try:
            # Generate conversation ID if not provided
            conversation_id = request.conversation_id or str(uuid.uuid4())

            # 1. Retrieve relevant documents
            search_results = await retrieval_service.hybrid_search(
                query=request.query,
                top_k=request.top_k or 5,
                filters=request.filters
            )

            # 2. Format context
            context = []
            sources = []
            for result in search_results:
                context.append({
                    "content": result.content,
                    "source": result.document_id
                })
                sources.append({
                    "chunk_id": result.chunk_id,
                    "document_id": result.document_id,
                    "score": result.score,
                    "reranked_score": result.reranked_score
                })

            # Send sources first
            yield f"data: {json.dumps({'type': 'sources', 'data': sources})}\n\n"

            # 3. Stream response from LLM
            full_response = []
            async for token in llm_service.stream_response(
                query=request.query,
                context=context,
                system_prompt="You are a helpful assistant. Answer the user's question based on the provided context."
            ):
                full_response.append(token)
                yield f"data: {json.dumps({'type': 'token', 'data': token})}\n\n"

            # Send completion
            yield f"data: {json.dumps({'type': 'done', 'conversation_id': conversation_id})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


@router.websocket("/ws/{conversation_id}")
async def chat_websocket(
    websocket: WebSocket,
    conversation_id: str,
    retrieval_service: RetrievalService = Depends(get_retrieval_service),
    llm_service: LLMService = Depends(get_llm_service)
):
    """
    WebSocket endpoint for real-time chat.

    Supports bidirectional communication for typing indicators,
    streaming responses, and session management.
    """
    await websocket.accept()

    try:
        while True:
            # Receive message from client
            message = await websocket.receive_json()

            message_type = message.get("type", "query")

            if message_type == "query":
                query = message["query"]
                filters = message.get("filters")
                top_k = message.get("top_k", 5)

                # 1. Retrieve documents
                search_results = await retrieval_service.hybrid_search(
                    query=query,
                    top_k=top_k,
                    filters=filters
                )

                # 2. Format context
                context = []
                for result in search_results:
                    context.append({
                        "content": result.content,
                        "source": result.document_id
                    })

                # 3. Stream response
                full_response = []
                async for token in llm_service.stream_response(
                    query=query,
                    context=context
                ):
                    await websocket.send_json({
                        "type": "token",
                        "data": token
                    })
                    full_response.append(token)

                # Send completion
                await websocket.send_json({
                    "type": "done",
                    "conversation_id": conversation_id
                })

            elif message_type == "ping":
                await websocket.send_json({"type": "pong"})

    except WebSocketDisconnect:
        # Handle disconnection
        pass
    except Exception as e:
        await websocket.send_json({
            "type": "error",
            "message": str(e)
        })


@router.get("/history/{conversation_id}", response_model=ChatHistoryResponse)
async def get_chat_history(
    conversation_id: str
) -> ChatHistoryResponse:
    """Get conversation history by ID."""
    if conversation_id in _conversations:
        return ChatHistoryResponse(
            conversation_id=conversation_id,
            messages=_conversations[conversation_id]
        )
    else:
        return ChatHistoryResponse(
            conversation_id=conversation_id,
            messages=[]
        )


@router.post("/clear/{conversation_id}")
async def clear_conversation(
    conversation_id: str
):
    """Clear conversation history."""
    if conversation_id in _conversations:
        del _conversations[conversation_id]

    return {"status": "success", "message": "Conversation cleared"}
